// Mocks generated by Mockito 5.4.6 from annotations
// in fitnesstracker/test/activity_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitnesstracker/model/activity_data.dart' as _i4;
import 'package:fitnesstracker/model/running_plan.dart' as _i5;
import 'package:fitnesstracker/repository/json_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [JsonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJsonRepository extends _i1.Mock implements _i2.JsonRepository {
  MockJsonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveActivity(_i4.ActivityData? activity) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveActivity,
          [activity],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.ActivityData>> retrieveActivities() =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveActivities,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.ActivityData>>.value(<_i4.ActivityData>[]),
      ) as _i3.Future<List<_i4.ActivityData>>);

  @override
  _i3.Future<void> saveRunningPlan(_i5.RunningPlanData? plan) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRunningPlan,
          [plan],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.RunningPlanData>> retrieveRunningPlans() =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveRunningPlans,
          [],
        ),
        returnValue: _i3.Future<List<_i5.RunningPlanData>>.value(
            <_i5.RunningPlanData>[]),
      ) as _i3.Future<List<_i5.RunningPlanData>>);
}
